#ifndef COPILOT_FACE_DATA_H
#define COPILOT_FACE_DATA_H

#include <stdint.h>

typedef enum {
    COPILOT_EXPR_IDLE = 0,
    COPILOT_EXPR_NEUTRAL = COPILOT_EXPR_IDLE,
    COPILOT_EXPR_HAPPY = COPILOT_EXPR_IDLE,
    COPILOT_EXPR_SAD = COPILOT_EXPR_IDLE,
    COPILOT_EXPR_ANGRY = COPILOT_EXPR_IDLE,
    COPILOT_EXPR_SLEEPY = COPILOT_EXPR_IDLE,
    COPILOT_EXPR_DIZZY = COPILOT_EXPR_IDLE,

    COPILOT_EXPR_SPEAKING = 1,
    COPILOT_EXPR_TALKING = COPILOT_EXPR_SPEAKING,
    COPILOT_EXPR_SURPRISED = COPILOT_EXPR_SPEAKING,

    COPILOT_EXPR_COUNT = 2
} copilot_expr_t;

#endif
